// The file contents for the current environment will overwrite these during build.
// The build system defaults to the dev environment which uses `environment.ts`, but if you do
// `ng build --env=prod` then `environment.prod.ts` will be used instead.
// The list of which env maps to which file can be found in `.angular-cli.json`.

// `.env.ts` is generated by the `npm run env` command
import env from './.env';
import {WebAuth} from 'auth0-js';

export const environment = {
  production: false,
  version: env.npm_package_version + '-dev',
  serverUrl: 'http://localhost:4993/api',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR',
    'es-AR'
  ]
};

export const auth0Config = new WebAuth({
  clientID: 'f7FmdAiwLajMwcePFLfBQ6QWO3q6UvGp',
  domain: 'mslaunches.auth0.com',
  responseType: 'token id_token',
  audience: environment.serverUrl,
  redirectUri: 'http://localhost:4200/',
  scope: 'openid profile email'
});
